blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: âœ¨ feat
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ ê°œë°œì„ ìœ„í•œ ì´ìŠˆ
    file: feature-task.yml

  - name: ğŸ fix
    description: ë²„ê·¸ ìˆ˜ì • ì‘ì—…ì„ ìœ„í•œ ì´ìŠˆ
    file: fix-task.yml

  - name: ğŸ”¨ refactor
    description: ì½”ë“œ ë¦¬íŒ©í† ë§ ì‘ì—… ì´ìŠˆ
    file: refactor-task.yml

  - name: ğŸ“ƒ docs
    description: ë¬¸ì„œ ì‘ì„± ë° ìˆ˜ì • ì‘ì—… ì´ìŠˆ
    file: docs-task.yml

  - name: âš™ï¸ chore
    description: ê°œë°œ í™˜ê²½ ì„¤ì • ê´€ë ¨ ì´ìŠˆ
    file: setting-task.yml

  - name: âœ… test
    description: í…ŒìŠ¤íŠ¸ ì½”ë“œ ì‘ì„± ë° í…ŒìŠ¤íŠ¸ í™˜ê²½ êµ¬ì¶•
    file: test-task.yml
    
  - name: ğŸ¨ style
    description: í…ŒìŠ¤íŠ¸ ì½”ë“œ ì‘ì„± ë° í…ŒìŠ¤íŠ¸ í™˜ê²½ êµ¬ì¶•
    file: style-task.yml
